---
openapi: 3.0.0
info:
    title: Carthage Shared Schemas
    description: The schemas shared between all the contexts
    version: 1.0.0
paths: { }
components:
    responses:
        LogManagementCollect.Accepted:
            description: The log collection request was accepted
        LogManagementCollect.BadRequest:
            description: The request is invalid
