---
openapi: 3.0.0
info:
    title: Carthage Shared Filters
    description: The filters for the shared resources
    version: 0.0.0
paths: {}
components:
    parameters:
        Shared.Pagination:
            name: Shared.Pagination
            in: query
            schema:
                $ref: "#/components/schemas/Shared.Pagination"
    schemas:
        Shared.Pagination:
            type: object
            additionalProperties: true
            properties:
                page:
                    type: integer
                    default: 1
                    minimum: 1
                    description: The page number for pagination. Defaults to 1.
                itemsPerPage:
                    type: integer
                    default: 20
                    minimum: 1
                    maximum: 2000
                    description: The number of items per page for pagination. Defaults to 20, with a
                        maximum of 2000.
