---
openapi: 3.0.0
info:
    title: Carthage Shared Filters
    description: The filters for the shared resources
    version: 0.0.0
paths: { }
components:
    parameters:
        Shared.Pagination.Page:
            name: page
            description: The page number for pagination. Defaults to 1.
            in: query
            required: false
            schema:
                $ref: "#/components/schemas/Shared.Pagination.Page"
        Shared.Pagination.ItemsPerPage:
            name: items_per_page
            description: The number of items per page for pagination. Defaults to 20, with a maximum of 2000.
            in: query
            required: false
            schema:
                $ref: "#/components/schemas/Shared.Pagination.ItemsPerPage"
    schemas:
        Shared.Pagination.Page:
            type: integer
            default: 1
            minimum: 1
        Shared.Pagination.ItemsPerPage:
            type: integer
            default: 20
            minimum: 1
            maximum: 2000
