---
openapi: 3.0.0
info:
    title: Carthage Shared Schemas
    description: The schemas shared between all the contexts
    version: 1.0.0
paths: { }
components:
    responses:
        Ping.Ok:
            description: Successful response containing the ping status
            content:
                application/json:
                    schema:
                        $ref: "Resource.yaml#/components/schemas/Shared.PingResource"
